ARG baseImageUri
ARG baseImageTag
FROM ${baseImageUri}:${baseImageTag}

ARG version
ARG mavenArtifactBaseUrl

ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss


# service war file

ADD ${mavenArtifactBaseUrl}/uk/gov/justice/services/cpp-platform-simulators/${version}/cpp-platform-simulators-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/cpp-platform-simulators-${version}.war


USER ${wildfly_user}
LABEL base_image ${baseImageTag}